### ISSUE TITLE
Перепроверьте текст задания.

### ISSUE THREAD

**Issue by andrey-ilyin** [ShiraseAkira/PS-Backend#1]
https://github.com/ShiraseAkira/PS-Backend/blob/d99907841e847010ba911f2c7252cf29edaf9626/LW0/task1.txt#L1

**Comment by ShiraseAkira** [comment]
Перепроверено, исправлено.

**Comment by andrey-ilyin** [comment]
Не вижу исправлений. Где смотреть?
